export const fakeEvents = [
    {
        id: 1,
        name: 'meetup',
        description: 'Lorem ipsum dolor sit amet, laborum maiores nostrum pariatur',
        beginDate: '2021-10-09T00:56:02+00:00',
        endDate: '2021-11-09T02:56:02+00:00',
        nbReservations: 15,
        limitReservation: 15,
        isSubscribed: false,
        country: '',
        department: '',
    },
    {
        id: 2,
        name: 'meetup js',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa dicta dolort laboriosam laborum maiores nostrum pariatur',
        beginDate: '2021-10-04T05:56:02+00:00',
        endDate: '2021-12-08T07:56:02+00:00',
        nbReservations: 15,
        limitReservation: 50,
        isSubscribed: false,
        country: '',
        department: '',
    },
    {
        id: 3,
        name: 'meetup php',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa dicta dolor dolorum, est fugit impedit ostrum pariatur',
        beginDate: '2021-10-08T03:56:02+00:00',
        endDate: '2021-10-08T05:56:02+00:00',
        nbReservations: 15,
        limitReservation: 50,
        isSubscribed: false,
        country: '',
        department: '',
    },
    {
        id: 4,
        name: 'meetup java',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa dicta dolor mpedit laboriosam laborum maiores nostrum pariatur',
        beginDate: '2021-11-09T00:26:02+00:00',
        endDate: '2021-11-09T00:56:02+00:00',
        nbReservations: 15,
        limitReservation: 50,
        isSubscribed: false,
        country: '',
        department: '',
    },
    {
        id: 5,
        name: 'Coupe de France',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cullaborum maiores nostrum pariatur',
        beginDate: '2021-11-09T00:26:02+00:00',
        endDate: '2021-11-09T00:56:02+00:00',
        nbReservations: 15,
        limitReservation: 15,
        isSubscribed: false,
        country: '',
        department: '',
    },
    {
        id: 6,
        name: 'Match de Ligue 1',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicit impedit laboriosam laborum maiores nostrum pariatur',
        beginDate: '2021-11-09T00:26:02+00:00',
        endDate: '2021-11-09T00:56:02+00:00',
        nbReservations: 15,
        limitReservation: 50,
        isSubscribed: false,
        country: '',
        department: '',
    },
]
